language: objective-c
osx_image: xcode8
xcode_project: WebBrowser.xcodeproj
xcode_scheme: WebBrowser
env:
  global:
  - FRAMEWORK_NAME=WebBrowser
  - EXAMPLE_SCHEME="WebBrowser"
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
before_script:
- carthage bootstrap
script:
  - xcodebuild -scheme "$EXAMPLE_SCHEME" -sdk iphonesimulator -project WebBrowser.xcodeproj -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty
